name: flutter_repo_search
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.2.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  retrofit_generator: ^8.0.3
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
